package com.zxdz.car.base.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.zxdz.car.main.model.domain.AdminCard;
import com.zxdz.car.main.model.domain.AreaInfo;
import com.zxdz.car.main.model.domain.CardInfo;
import com.zxdz.car.main.model.domain.CarTravelRecord;
import com.zxdz.car.main.model.domain.ChangePolice;
import com.zxdz.car.main.model.domain.ChangePoliceInfo;
import com.zxdz.car.main.model.domain.DriverInfo;
import com.zxdz.car.main.model.domain.PictureInfo;
import com.zxdz.car.main.model.domain.PoliceInfo;
import com.zxdz.car.main.model.domain.PoliceInfoAll;
import com.zxdz.car.main.model.domain.RouteInfo;
import com.zxdz.car.main.model.domain.ServerIP;
import com.zxdz.car.main.model.domain.TerminalInfo;
import com.zxdz.car.main.model.domain.TrailPointInfo;
import com.zxdz.car.main.model.domain.UnWarnInfo;
import com.zxdz.car.main.model.domain.WarnInfo;

import com.zxdz.car.base.dao.AdminCardDao;
import com.zxdz.car.base.dao.AreaInfoDao;
import com.zxdz.car.base.dao.CardInfoDao;
import com.zxdz.car.base.dao.CarTravelRecordDao;
import com.zxdz.car.base.dao.ChangePoliceDao;
import com.zxdz.car.base.dao.ChangePoliceInfoDao;
import com.zxdz.car.base.dao.DriverInfoDao;
import com.zxdz.car.base.dao.PictureInfoDao;
import com.zxdz.car.base.dao.PoliceInfoDao;
import com.zxdz.car.base.dao.PoliceInfoAllDao;
import com.zxdz.car.base.dao.RouteInfoDao;
import com.zxdz.car.base.dao.ServerIPDao;
import com.zxdz.car.base.dao.TerminalInfoDao;
import com.zxdz.car.base.dao.TrailPointInfoDao;
import com.zxdz.car.base.dao.UnWarnInfoDao;
import com.zxdz.car.base.dao.WarnInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig adminCardDaoConfig;
    private final DaoConfig areaInfoDaoConfig;
    private final DaoConfig cardInfoDaoConfig;
    private final DaoConfig carTravelRecordDaoConfig;
    private final DaoConfig changePoliceDaoConfig;
    private final DaoConfig changePoliceInfoDaoConfig;
    private final DaoConfig driverInfoDaoConfig;
    private final DaoConfig pictureInfoDaoConfig;
    private final DaoConfig policeInfoDaoConfig;
    private final DaoConfig policeInfoAllDaoConfig;
    private final DaoConfig routeInfoDaoConfig;
    private final DaoConfig serverIPDaoConfig;
    private final DaoConfig terminalInfoDaoConfig;
    private final DaoConfig trailPointInfoDaoConfig;
    private final DaoConfig unWarnInfoDaoConfig;
    private final DaoConfig warnInfoDaoConfig;

    private final AdminCardDao adminCardDao;
    private final AreaInfoDao areaInfoDao;
    private final CardInfoDao cardInfoDao;
    private final CarTravelRecordDao carTravelRecordDao;
    private final ChangePoliceDao changePoliceDao;
    private final ChangePoliceInfoDao changePoliceInfoDao;
    private final DriverInfoDao driverInfoDao;
    private final PictureInfoDao pictureInfoDao;
    private final PoliceInfoDao policeInfoDao;
    private final PoliceInfoAllDao policeInfoAllDao;
    private final RouteInfoDao routeInfoDao;
    private final ServerIPDao serverIPDao;
    private final TerminalInfoDao terminalInfoDao;
    private final TrailPointInfoDao trailPointInfoDao;
    private final UnWarnInfoDao unWarnInfoDao;
    private final WarnInfoDao warnInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        adminCardDaoConfig = daoConfigMap.get(AdminCardDao.class).clone();
        adminCardDaoConfig.initIdentityScope(type);

        areaInfoDaoConfig = daoConfigMap.get(AreaInfoDao.class).clone();
        areaInfoDaoConfig.initIdentityScope(type);

        cardInfoDaoConfig = daoConfigMap.get(CardInfoDao.class).clone();
        cardInfoDaoConfig.initIdentityScope(type);

        carTravelRecordDaoConfig = daoConfigMap.get(CarTravelRecordDao.class).clone();
        carTravelRecordDaoConfig.initIdentityScope(type);

        changePoliceDaoConfig = daoConfigMap.get(ChangePoliceDao.class).clone();
        changePoliceDaoConfig.initIdentityScope(type);

        changePoliceInfoDaoConfig = daoConfigMap.get(ChangePoliceInfoDao.class).clone();
        changePoliceInfoDaoConfig.initIdentityScope(type);

        driverInfoDaoConfig = daoConfigMap.get(DriverInfoDao.class).clone();
        driverInfoDaoConfig.initIdentityScope(type);

        pictureInfoDaoConfig = daoConfigMap.get(PictureInfoDao.class).clone();
        pictureInfoDaoConfig.initIdentityScope(type);

        policeInfoDaoConfig = daoConfigMap.get(PoliceInfoDao.class).clone();
        policeInfoDaoConfig.initIdentityScope(type);

        policeInfoAllDaoConfig = daoConfigMap.get(PoliceInfoAllDao.class).clone();
        policeInfoAllDaoConfig.initIdentityScope(type);

        routeInfoDaoConfig = daoConfigMap.get(RouteInfoDao.class).clone();
        routeInfoDaoConfig.initIdentityScope(type);

        serverIPDaoConfig = daoConfigMap.get(ServerIPDao.class).clone();
        serverIPDaoConfig.initIdentityScope(type);

        terminalInfoDaoConfig = daoConfigMap.get(TerminalInfoDao.class).clone();
        terminalInfoDaoConfig.initIdentityScope(type);

        trailPointInfoDaoConfig = daoConfigMap.get(TrailPointInfoDao.class).clone();
        trailPointInfoDaoConfig.initIdentityScope(type);

        unWarnInfoDaoConfig = daoConfigMap.get(UnWarnInfoDao.class).clone();
        unWarnInfoDaoConfig.initIdentityScope(type);

        warnInfoDaoConfig = daoConfigMap.get(WarnInfoDao.class).clone();
        warnInfoDaoConfig.initIdentityScope(type);

        adminCardDao = new AdminCardDao(adminCardDaoConfig, this);
        areaInfoDao = new AreaInfoDao(areaInfoDaoConfig, this);
        cardInfoDao = new CardInfoDao(cardInfoDaoConfig, this);
        carTravelRecordDao = new CarTravelRecordDao(carTravelRecordDaoConfig, this);
        changePoliceDao = new ChangePoliceDao(changePoliceDaoConfig, this);
        changePoliceInfoDao = new ChangePoliceInfoDao(changePoliceInfoDaoConfig, this);
        driverInfoDao = new DriverInfoDao(driverInfoDaoConfig, this);
        pictureInfoDao = new PictureInfoDao(pictureInfoDaoConfig, this);
        policeInfoDao = new PoliceInfoDao(policeInfoDaoConfig, this);
        policeInfoAllDao = new PoliceInfoAllDao(policeInfoAllDaoConfig, this);
        routeInfoDao = new RouteInfoDao(routeInfoDaoConfig, this);
        serverIPDao = new ServerIPDao(serverIPDaoConfig, this);
        terminalInfoDao = new TerminalInfoDao(terminalInfoDaoConfig, this);
        trailPointInfoDao = new TrailPointInfoDao(trailPointInfoDaoConfig, this);
        unWarnInfoDao = new UnWarnInfoDao(unWarnInfoDaoConfig, this);
        warnInfoDao = new WarnInfoDao(warnInfoDaoConfig, this);

        registerDao(AdminCard.class, adminCardDao);
        registerDao(AreaInfo.class, areaInfoDao);
        registerDao(CardInfo.class, cardInfoDao);
        registerDao(CarTravelRecord.class, carTravelRecordDao);
        registerDao(ChangePolice.class, changePoliceDao);
        registerDao(ChangePoliceInfo.class, changePoliceInfoDao);
        registerDao(DriverInfo.class, driverInfoDao);
        registerDao(PictureInfo.class, pictureInfoDao);
        registerDao(PoliceInfo.class, policeInfoDao);
        registerDao(PoliceInfoAll.class, policeInfoAllDao);
        registerDao(RouteInfo.class, routeInfoDao);
        registerDao(ServerIP.class, serverIPDao);
        registerDao(TerminalInfo.class, terminalInfoDao);
        registerDao(TrailPointInfo.class, trailPointInfoDao);
        registerDao(UnWarnInfo.class, unWarnInfoDao);
        registerDao(WarnInfo.class, warnInfoDao);
    }
    
    public void clear() {
        adminCardDaoConfig.clearIdentityScope();
        areaInfoDaoConfig.clearIdentityScope();
        cardInfoDaoConfig.clearIdentityScope();
        carTravelRecordDaoConfig.clearIdentityScope();
        changePoliceDaoConfig.clearIdentityScope();
        changePoliceInfoDaoConfig.clearIdentityScope();
        driverInfoDaoConfig.clearIdentityScope();
        pictureInfoDaoConfig.clearIdentityScope();
        policeInfoDaoConfig.clearIdentityScope();
        policeInfoAllDaoConfig.clearIdentityScope();
        routeInfoDaoConfig.clearIdentityScope();
        serverIPDaoConfig.clearIdentityScope();
        terminalInfoDaoConfig.clearIdentityScope();
        trailPointInfoDaoConfig.clearIdentityScope();
        unWarnInfoDaoConfig.clearIdentityScope();
        warnInfoDaoConfig.clearIdentityScope();
    }

    public AdminCardDao getAdminCardDao() {
        return adminCardDao;
    }

    public AreaInfoDao getAreaInfoDao() {
        return areaInfoDao;
    }

    public CardInfoDao getCardInfoDao() {
        return cardInfoDao;
    }

    public CarTravelRecordDao getCarTravelRecordDao() {
        return carTravelRecordDao;
    }

    public ChangePoliceDao getChangePoliceDao() {
        return changePoliceDao;
    }

    public ChangePoliceInfoDao getChangePoliceInfoDao() {
        return changePoliceInfoDao;
    }

    public DriverInfoDao getDriverInfoDao() {
        return driverInfoDao;
    }

    public PictureInfoDao getPictureInfoDao() {
        return pictureInfoDao;
    }

    public PoliceInfoDao getPoliceInfoDao() {
        return policeInfoDao;
    }

    public PoliceInfoAllDao getPoliceInfoAllDao() {
        return policeInfoAllDao;
    }

    public RouteInfoDao getRouteInfoDao() {
        return routeInfoDao;
    }

    public ServerIPDao getServerIPDao() {
        return serverIPDao;
    }

    public TerminalInfoDao getTerminalInfoDao() {
        return terminalInfoDao;
    }

    public TrailPointInfoDao getTrailPointInfoDao() {
        return trailPointInfoDao;
    }

    public UnWarnInfoDao getUnWarnInfoDao() {
        return unWarnInfoDao;
    }

    public WarnInfoDao getWarnInfoDao() {
        return warnInfoDao;
    }

}
