package com.zxdz.car.base.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.zxdz.car.main.model.domain.PictureInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PICTURE_INFO".
*/
public class PictureInfoDao extends AbstractDao<PictureInfo, Long> {

    public static final String TABLENAME = "PICTURE_INFO";

    /**
     * Properties of entity PictureInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property LsId = new Property(1, int.class, "lsId", false, "LS_ID");
        public final static Property GjpzSJ = new Property(2, java.util.Date.class, "gjpzSJ", false, "GJPZ_SJ");
        public final static Property Picture = new Property(3, String.class, "picture", false, "PICTURE");
    }


    public PictureInfoDao(DaoConfig config) {
        super(config);
    }
    
    public PictureInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PICTURE_INFO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"LS_ID\" INTEGER NOT NULL ," + // 1: lsId
                "\"GJPZ_SJ\" INTEGER," + // 2: gjpzSJ
                "\"PICTURE\" TEXT);"); // 3: picture
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PICTURE_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, PictureInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getLsId());
 
        java.util.Date gjpzSJ = entity.getGjpzSJ();
        if (gjpzSJ != null) {
            stmt.bindLong(3, gjpzSJ.getTime());
        }
 
        String picture = entity.getPicture();
        if (picture != null) {
            stmt.bindString(4, picture);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, PictureInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getLsId());
 
        java.util.Date gjpzSJ = entity.getGjpzSJ();
        if (gjpzSJ != null) {
            stmt.bindLong(3, gjpzSJ.getTime());
        }
 
        String picture = entity.getPicture();
        if (picture != null) {
            stmt.bindString(4, picture);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public PictureInfo readEntity(Cursor cursor, int offset) {
        PictureInfo entity = new PictureInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // lsId
            cursor.isNull(offset + 2) ? null : new java.util.Date(cursor.getLong(offset + 2)), // gjpzSJ
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // picture
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, PictureInfo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setLsId(cursor.getInt(offset + 1));
        entity.setGjpzSJ(cursor.isNull(offset + 2) ? null : new java.util.Date(cursor.getLong(offset + 2)));
        entity.setPicture(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(PictureInfo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(PictureInfo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(PictureInfo entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
