package com.zxdz.car.base.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.zxdz.car.main.model.domain.PoliceInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "POLICE_INFO".
*/
public class PoliceInfoDao extends AbstractDao<PoliceInfo, Long> {

    public static final String TABLENAME = "POLICE_INFO";

    /**
     * Properties of entity PoliceInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property DLGJ_LYKH = new Property(1, String.class, "DLGJ_LYKH", false, "DLGJ__LYKH");
        public final static Property DLGJ_LYSJ = new Property(2, java.util.Date.class, "DLGJ_LYSJ", false, "DLGJ__LYSJ");
        public final static Property DLGJ_LYXM = new Property(3, String.class, "DLGJ_LYXM", false, "DLGJ__LYXM");
        public final static Property DLGJ_LYJH = new Property(4, String.class, "DLGJ_LYJH", false, "DLGJ__LYJH");
        public final static Property DLGJ_LYBM = new Property(5, String.class, "DLGJ_LYBM", false, "DLGJ__LYBM");
        public final static Property DLGJ_JHKH = new Property(6, String.class, "DLGJ_JHKH", false, "DLGJ__JHKH");
        public final static Property DLGJ_JHSJ = new Property(7, java.util.Date.class, "DLGJ_JHSJ", false, "DLGJ__JHSJ");
        public final static Property DLGJ_JHXM = new Property(8, String.class, "DLGJ_JHXM", false, "DLGJ__JHXM");
        public final static Property DLGJ_JHJH = new Property(9, String.class, "DLGJ_JHJH", false, "DLGJ__JHJH");
        public final static Property DLGJ_JHBM = new Property(10, String.class, "DLGJ_JHBM", false, "DLGJ__JHBM");
    }


    public PoliceInfoDao(DaoConfig config) {
        super(config);
    }
    
    public PoliceInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"POLICE_INFO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"DLGJ__LYKH\" TEXT," + // 1: DLGJ_LYKH
                "\"DLGJ__LYSJ\" INTEGER," + // 2: DLGJ_LYSJ
                "\"DLGJ__LYXM\" TEXT," + // 3: DLGJ_LYXM
                "\"DLGJ__LYJH\" TEXT," + // 4: DLGJ_LYJH
                "\"DLGJ__LYBM\" TEXT," + // 5: DLGJ_LYBM
                "\"DLGJ__JHKH\" TEXT," + // 6: DLGJ_JHKH
                "\"DLGJ__JHSJ\" INTEGER," + // 7: DLGJ_JHSJ
                "\"DLGJ__JHXM\" TEXT," + // 8: DLGJ_JHXM
                "\"DLGJ__JHJH\" TEXT," + // 9: DLGJ_JHJH
                "\"DLGJ__JHBM\" TEXT);"); // 10: DLGJ_JHBM
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"POLICE_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, PoliceInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String DLGJ_LYKH = entity.getDLGJ_LYKH();
        if (DLGJ_LYKH != null) {
            stmt.bindString(2, DLGJ_LYKH);
        }
 
        java.util.Date DLGJ_LYSJ = entity.getDLGJ_LYSJ();
        if (DLGJ_LYSJ != null) {
            stmt.bindLong(3, DLGJ_LYSJ.getTime());
        }
 
        String DLGJ_LYXM = entity.getDLGJ_LYXM();
        if (DLGJ_LYXM != null) {
            stmt.bindString(4, DLGJ_LYXM);
        }
 
        String DLGJ_LYJH = entity.getDLGJ_LYJH();
        if (DLGJ_LYJH != null) {
            stmt.bindString(5, DLGJ_LYJH);
        }
 
        String DLGJ_LYBM = entity.getDLGJ_LYBM();
        if (DLGJ_LYBM != null) {
            stmt.bindString(6, DLGJ_LYBM);
        }
 
        String DLGJ_JHKH = entity.getDLGJ_JHKH();
        if (DLGJ_JHKH != null) {
            stmt.bindString(7, DLGJ_JHKH);
        }
 
        java.util.Date DLGJ_JHSJ = entity.getDLGJ_JHSJ();
        if (DLGJ_JHSJ != null) {
            stmt.bindLong(8, DLGJ_JHSJ.getTime());
        }
 
        String DLGJ_JHXM = entity.getDLGJ_JHXM();
        if (DLGJ_JHXM != null) {
            stmt.bindString(9, DLGJ_JHXM);
        }
 
        String DLGJ_JHJH = entity.getDLGJ_JHJH();
        if (DLGJ_JHJH != null) {
            stmt.bindString(10, DLGJ_JHJH);
        }
 
        String DLGJ_JHBM = entity.getDLGJ_JHBM();
        if (DLGJ_JHBM != null) {
            stmt.bindString(11, DLGJ_JHBM);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, PoliceInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String DLGJ_LYKH = entity.getDLGJ_LYKH();
        if (DLGJ_LYKH != null) {
            stmt.bindString(2, DLGJ_LYKH);
        }
 
        java.util.Date DLGJ_LYSJ = entity.getDLGJ_LYSJ();
        if (DLGJ_LYSJ != null) {
            stmt.bindLong(3, DLGJ_LYSJ.getTime());
        }
 
        String DLGJ_LYXM = entity.getDLGJ_LYXM();
        if (DLGJ_LYXM != null) {
            stmt.bindString(4, DLGJ_LYXM);
        }
 
        String DLGJ_LYJH = entity.getDLGJ_LYJH();
        if (DLGJ_LYJH != null) {
            stmt.bindString(5, DLGJ_LYJH);
        }
 
        String DLGJ_LYBM = entity.getDLGJ_LYBM();
        if (DLGJ_LYBM != null) {
            stmt.bindString(6, DLGJ_LYBM);
        }
 
        String DLGJ_JHKH = entity.getDLGJ_JHKH();
        if (DLGJ_JHKH != null) {
            stmt.bindString(7, DLGJ_JHKH);
        }
 
        java.util.Date DLGJ_JHSJ = entity.getDLGJ_JHSJ();
        if (DLGJ_JHSJ != null) {
            stmt.bindLong(8, DLGJ_JHSJ.getTime());
        }
 
        String DLGJ_JHXM = entity.getDLGJ_JHXM();
        if (DLGJ_JHXM != null) {
            stmt.bindString(9, DLGJ_JHXM);
        }
 
        String DLGJ_JHJH = entity.getDLGJ_JHJH();
        if (DLGJ_JHJH != null) {
            stmt.bindString(10, DLGJ_JHJH);
        }
 
        String DLGJ_JHBM = entity.getDLGJ_JHBM();
        if (DLGJ_JHBM != null) {
            stmt.bindString(11, DLGJ_JHBM);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public PoliceInfo readEntity(Cursor cursor, int offset) {
        PoliceInfo entity = new PoliceInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // DLGJ_LYKH
            cursor.isNull(offset + 2) ? null : new java.util.Date(cursor.getLong(offset + 2)), // DLGJ_LYSJ
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // DLGJ_LYXM
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // DLGJ_LYJH
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // DLGJ_LYBM
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // DLGJ_JHKH
            cursor.isNull(offset + 7) ? null : new java.util.Date(cursor.getLong(offset + 7)), // DLGJ_JHSJ
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // DLGJ_JHXM
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // DLGJ_JHJH
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10) // DLGJ_JHBM
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, PoliceInfo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDLGJ_LYKH(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setDLGJ_LYSJ(cursor.isNull(offset + 2) ? null : new java.util.Date(cursor.getLong(offset + 2)));
        entity.setDLGJ_LYXM(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setDLGJ_LYJH(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setDLGJ_LYBM(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setDLGJ_JHKH(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setDLGJ_JHSJ(cursor.isNull(offset + 7) ? null : new java.util.Date(cursor.getLong(offset + 7)));
        entity.setDLGJ_JHXM(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setDLGJ_JHJH(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setDLGJ_JHBM(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(PoliceInfo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(PoliceInfo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(PoliceInfo entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
