package com.zxdz.car.base.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.zxdz.car.main.model.domain.RouteInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ROUTE_INFO".
*/
public class RouteInfoDao extends AbstractDao<RouteInfo, Long> {

    public static final String TABLENAME = "ROUTE_INFO";

    /**
     * Properties of entity RouteInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property RouteId = new Property(1, String.class, "routeId", false, "ROUTE_ID");
        public final static Property AreaId = new Property(2, String.class, "areaId", false, "AREA_ID");
        public final static Property RouteRange = new Property(3, String.class, "routeRange", false, "ROUTE_RANGE");
    }


    public RouteInfoDao(DaoConfig config) {
        super(config);
    }
    
    public RouteInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ROUTE_INFO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"ROUTE_ID\" TEXT," + // 1: routeId
                "\"AREA_ID\" TEXT," + // 2: areaId
                "\"ROUTE_RANGE\" TEXT);"); // 3: routeRange
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ROUTE_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, RouteInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String routeId = entity.getRouteId();
        if (routeId != null) {
            stmt.bindString(2, routeId);
        }
 
        String areaId = entity.getAreaId();
        if (areaId != null) {
            stmt.bindString(3, areaId);
        }
 
        String routeRange = entity.getRouteRange();
        if (routeRange != null) {
            stmt.bindString(4, routeRange);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, RouteInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String routeId = entity.getRouteId();
        if (routeId != null) {
            stmt.bindString(2, routeId);
        }
 
        String areaId = entity.getAreaId();
        if (areaId != null) {
            stmt.bindString(3, areaId);
        }
 
        String routeRange = entity.getRouteRange();
        if (routeRange != null) {
            stmt.bindString(4, routeRange);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public RouteInfo readEntity(Cursor cursor, int offset) {
        RouteInfo entity = new RouteInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // routeId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // areaId
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // routeRange
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, RouteInfo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setRouteId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setAreaId(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setRouteRange(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(RouteInfo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(RouteInfo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(RouteInfo entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
