package com.zxdz.car.base.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.zxdz.car.main.model.domain.ServerIP;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SERVER_IP".
*/
public class ServerIPDao extends AbstractDao<ServerIP, Long> {

    public static final String TABLENAME = "SERVER_IP";

    /**
     * Properties of entity ServerIP.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Ip = new Property(1, String.class, "ip", false, "IP");
        public final static Property PersonID = new Property(2, String.class, "personID", false, "PERSON_ID");
        public final static Property Personfactory = new Property(3, String.class, "personfactory", false, "PERSONFACTORY");
    }


    public ServerIPDao(DaoConfig config) {
        super(config);
    }
    
    public ServerIPDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SERVER_IP\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"IP\" TEXT," + // 1: ip
                "\"PERSON_ID\" TEXT," + // 2: personID
                "\"PERSONFACTORY\" TEXT);"); // 3: personfactory
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SERVER_IP\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ServerIP entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String ip = entity.getIp();
        if (ip != null) {
            stmt.bindString(2, ip);
        }
 
        String personID = entity.getPersonID();
        if (personID != null) {
            stmt.bindString(3, personID);
        }
 
        String personfactory = entity.getPersonfactory();
        if (personfactory != null) {
            stmt.bindString(4, personfactory);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ServerIP entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String ip = entity.getIp();
        if (ip != null) {
            stmt.bindString(2, ip);
        }
 
        String personID = entity.getPersonID();
        if (personID != null) {
            stmt.bindString(3, personID);
        }
 
        String personfactory = entity.getPersonfactory();
        if (personfactory != null) {
            stmt.bindString(4, personfactory);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ServerIP readEntity(Cursor cursor, int offset) {
        ServerIP entity = new ServerIP( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // ip
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // personID
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // personfactory
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ServerIP entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setIp(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setPersonID(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setPersonfactory(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ServerIP entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ServerIP entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ServerIP entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
